sudo: required
language: android

jdk:
  - oraclejdk8

env:
  global:
    - TARGET_SDK=26
    - BUILD_TOOLS_VERSION=26.0.0
  matrix:
    - EMULATOR_SDK=android-19 ABI=armeabi-v7a
    - EMULATOR_SDK=android-22 ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-${TARGET_SDK}
    - android-19
    - android-22
    - build-tools-${BUILD_TOOLS_VERSION}
    - extra-android-m2repository

before_script:
  - android-update-sdk --components=sys-img-$ABI-$EMULATOR_SDK --accept-licenses='android-sdk-license-[0-9a-f]{8}'
  - echo no | android create avd --force -n test -t $EMULATOR_SDK --abi $ABI
  - emulator -avd test -no-audio -no-window &
  - ./gradlew clean assembleDebug assembleDebugAndroidTest
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - travis_wait 60 ./gradlew jacocoDebugTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
